### ISSUE TITLE
Moving toolchain include inside else statement fixes first-time CMake generation

### ISSUE THREAD

**Issue by DatCaptainHorse** [REGoth-project/Automate-VCPKG#2]
Hey! I like your helpful script, saved me from some headaches.. had to do a small modification though. If you are still maintaining this here is what I did:

From here: [line 97](https://github.com/REGoth-project/Automate-VCPKG/blob/master/automate-vcpkg.cmake#L97)
To here: [line 100](https://github.com/REGoth-project/Automate-VCPKG/blob/master/automate-vcpkg.cmake#L100)

From my testing, those can be moved under else statement [at line 92](https://github.com/REGoth-project/Automate-VCPKG/blob/master/automate-vcpkg.cmake#L92) to fix first-time CMake generation complaining about missing file for the include.
```
else()
    set(VCPKG_ROOT $ENV{VCPKG_ROOT})

    # We know this wasn't set before so we need point the toolchain file to the newly found VCPKG_ROOT
    set(CMAKE_TOOLCHAIN_FILE ${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake CACHE STRING "")

    # Just setting vcpkg.cmake as toolchain file does not seem to actually pull in the code
    include(${VCPKG_ROOT}/scripts/buildsystems/vcpkg.cmake)
endif()
```

**Comment by DatCaptainHorse** [comment]
Belay that, after cleaning cache CMAKE_TOOLCHAIN_FILE is obviously not set.. 😅
Not sure why CMake has difficulties with `include could not find requested file` still, I'll need to just workaround it by calling CMake generation twice..

**Comment by ataulien** [comment]
Hi! Great that the script could help you! Do you mind sending a pull-request with your changes?

**Comment by DatCaptainHorse** [comment]
Pull request has been made [PR#3](https://github.com/REGoth-project/Automate-VCPKG/pull/3)
This issue can be closed if no longer needed.

**Comment by ataulien** [comment]
Thank you for the fix!
